wandb_version: 1

run_name:
  desc: null
  value: test
dataset_name:
  desc: null
  value: HYPOXIA_9K
seed:
  desc: null
  value: 42
ntokens:
  desc: null
  value: 10000
d_model:
  desc: null
  value: 512
nhead:
  desc: null
  value: 8
d_hid:
  desc: null
  value: 2048
nlayers:
  desc: null
  value: 6
n_bins:
  desc: null
  value: 51
n_hvg:
  desc: null
  value: 100
include_zero_gene:
  desc: null
  value: false
mask_single_value:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0001
amp:
  desc: null
  value: true
schedule_ratio:
  desc: null
  value: 0.9
GEPC:
  desc: null
  value: false
explicit_zero_prob:
  desc: null
  value: true
do_train:
  desc: null
  value: true
log_interval:
  desc: null
  value: 100
wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722523112
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
